window.NIJI_GAMES = [
  {id:'tensec',title:'10びょうチャレンジ',icon:'⏱️',cat:'じかん・抑制',desc:'「いま10秒！」と思った瞬間に止める体内時計ゲーム',tags:['自立活動','時間']},
  {id:'directions',title:'うえ・した・みぎ・ひだり',icon:'🧭',cat:'ビジョン',desc:'表示された方向をすばやくタップ',tags:['空間認知','反応']},
  {id:'janken',title:'ジャンケンをおぼえよう',icon:'✊',cat:'SST',desc:'学習モードと勝負モードでルールを練習',tags:['ルール','SST']},
  {id:'colorquiz',title:'色の名前 3択クイズ',icon:'🎨',cat:'認知',desc:'色を見て正しい名前を選ぶ',tags:['色','3択']},
  {id:'stick',title:'棒キャッチ',icon:'🪄',cat:'ビジョン',desc:'落ちてくる棒をギリギリでタップしてキャッチ',tags:['反応','タイミング']},
  {id:'maze',title:'ビジョン迷路',icon:'🌀',cat:'ビジョン',desc:'レベルが上がるほど長くなる迷路',tags:['眼球運動','集中']},
  {id:'bottle',title:'ボトルフリップ',icon:'🧴',cat:'息抜き',desc:'タップで回転。成功すると台が小さくなる',tags:['タイミング','レベル']},
  {id:'slide15',title:'スライドパズル15',icon:'🔢',cat:'認知',desc:'1〜15を順番にそろえる定番パズル',tags:['位置','順序']},
  {id:'girigiri',title:'ギリギリストップ',icon:'🎯',cat:'じかん・抑制',desc:'動く点をゴール直前で止める',tags:['抑制','タイミング']},
  {id:'bomb',title:'落下ターゲットシューティング',icon:'🎯',cat:'ビジョン',desc:'落ちてくるターゲットをタップして撃ち落とす',tags:['追視','反応']},
  {id:'bugfind',title:'ちいさな虫をさがせ',icon:'🔎',cat:'ビジョン',desc:'たくさんの中から指定された虫を見つける',tags:['探索','選択注意']},
  {id:'bugcatch',title:'虫とりゲーム',icon:'🦋',cat:'ビジョン',desc:'動く虫を時間内にたくさんタップ',tags:['追視','注意']},
  {id:'tap10',title:'ちいさい順にタップ 1〜10',icon:'1️⃣',cat:'ビジョン',desc:'散らばった数字を1から順に探してタップ',tags:['探索','数系列']},
  {id:'tap50',title:'タップで50',icon:'5️⃣',cat:'ビジョン',desc:'1〜50を順番にすばやくタップ',tags:['探索','集中']},
  {id:'make10',title:'足して10を作れ',icon:'🔟',cat:'算数',desc:'2つの数字を選んで10になるペアを消す',tags:['補数','たし算']},
  {id:'make10drop',title:'あわせて10 ブロック',icon:'🧱',cat:'算数',desc:'隣り合う数字で10を作り連鎖を狙う',tags:['補数','パズル']},
  {id:'multblock',title:'かけ算ブロック',icon:'✖️',cat:'算数',desc:'式と答えのペアを見つけてブロックを消す',tags:['九九','パズル']},
  {id:'primeblock',title:'素数ブロック',icon:'💎',cat:'算数',desc:'素数だけを見つけてタップする数字ゲーム',tags:['素数','判断']},
  {id:'numorder',title:'かずならべ 1〜100',icon:'🔢',cat:'算数',desc:'数字を小さい順に並べるタイムアタック',tags:['数系列','1〜100']},
  {id:'shapequiz',title:'図形なまえクイズ',icon:'🔺',cat:'算数',desc:'表示された図形の名前を3択で答える',tags:['図形','3択']},
  {id:'divisor',title:'約数をみつけよう',icon:'🧮',cat:'算数',desc:'指定された数の約数をすべて選ぶ',tags:['約数','高学年']},
  {id:'commondiv',title:'公約数をみつけよう',icon:'🤝',cat:'算数',desc:'2つの数に共通する約数を選ぶ',tags:['公約数','高学年']},
  {id:'commonmult',title:'公倍数をみつけよう',icon:'🔁',cat:'算数',desc:'2つの数の公倍数を選ぶ',tags:['公倍数','高学年']},
  {id:'calcmaze',title:'けいさんめいろ',icon:'➕',cat:'算数',desc:'正しい計算答えを選びながらゴールへ進む',tags:['計算','迷路']},
  {id:'hiramemory',title:'ひらがな すいじゃく',icon:'🃏',cat:'国語',desc:'同じひらがなのペアをそろえる神経衰弱',tags:['ひらがな','記憶']},
  {id:'hiraarrange',title:'ひらがなならべ',icon:'あ',cat:'国語',desc:'ばらばらの文字を並べて言葉を作る',tags:['語彙','並べ替え']},
  {id:'kataarrange',title:'カタカナならべ',icon:'ア',cat:'国語',desc:'ばらばらのカタカナを並べて言葉を作る',tags:['カタカナ','並べ替え']},
  {id:'hirasearch',title:'ことばさがし（ひらがな）',icon:'🔍',cat:'国語',desc:'文字の中から指定された言葉を見つける',tags:['探索','ひらがな']},
  {id:'katasearch',title:'ことばさがし（カタカナ）',icon:'🔎',cat:'国語',desc:'文字の中から指定された言葉を見つける',tags:['探索','カタカナ']},
  {id:'idiomarrange',title:'四字熟語ならべ',icon:'四',cat:'国語',desc:'4つの漢字を正しい順に並べる',tags:['熟語','並べ替え']},
  {id:'story',title:'いつ・どこで・だれが・どうした',icon:'📖',cat:'国語',desc:'カードをめくって思いがけない文を作る',tags:['文章構成','ことば']},
  {id:'continents',title:'6大陸と3海洋',icon:'🌏',cat:'社会',desc:'大陸・海洋の名前をクイズで覚える',tags:['地理','世界']},
  {id:'prefecture',title:'都道府県クイズ',icon:'🗾',cat:'社会',desc:'地方や特徴から都道府県名を当てる',tags:['地理','日本']},
  {id:'dice',title:'Webサイコロ',icon:'🎲',cat:'レク',desc:'1〜9個まで同時に振れるサイコロ',tags:['レク','道具']},
  {id:'roulette',title:'Webルーレット',icon:'🎡',cat:'レク',desc:'メンバーやお題を登録して公平に抽選',tags:['抽選','鬼決め']},
  {id:'bingo',title:'ビンゴマシン',icon:'🎱',cat:'レク',desc:'1〜75の数字をランダム抽選',tags:['レク','抽選']},
  {id:'dicetalk',title:'サイコロトーク',icon:'💬',cat:'SST',desc:'出た目のお題で自分のことを話す',tags:['会話','自己理解']},
  {id:'traffic',title:'信号機ルール',icon:'🚦',cat:'SST',desc:'信号を見て「進む・止まる」を判断',tags:['安全','判断']},
  {id:'words',title:'チクチク・ふわふわ言葉',icon:'💭',cat:'SST',desc:'相手がうれしい言葉か傷つく言葉かを考える',tags:['言葉','対人']},
  {id:'dayword',title:'きょう・あした・きのう',icon:'📅',cat:'認知',desc:'日付の前後関係をクイズで確認',tags:['時間概念','日付']},
  {id:'shopping',title:'いくら、はらう？',icon:'🛒',cat:'生活',desc:'商品代金ぴったりのお金を選んで支払う',tags:['お金','生活']},
  {id:'stamp',title:'にくきゅうスタンプ',icon:'🐾',cat:'息抜き',desc:'好きな場所をタップして肉球を増やす',tags:['リラックス','タップ']},
  {id:'shapeDrop',title:'ずけい・ドロップ',icon:'🔷',cat:'息抜き',desc:'タップした場所から図形があふれる感覚遊び',tags:['感覚','タップ']},
  {id:'moraread',title:'ここよんで！',icon:'👆',cat:'国語',desc:'文字を1拍ずつタップして音のまとまりを確認',tags:['モーラ','読み']},
  {id:'kanjipuzzle',title:'漢字をバラバラにしちゃおう',icon:'🧩',cat:'国語',desc:'漢字のパーツを組み合わせて1文字を作る',tags:['漢字','構成']},
  {id:'bushu',title:'ぶしゅ はっけん！',icon:'🔍',cat:'国語',desc:'漢字の中から部首を見つけるクイズ',tags:['漢字','部首']},
  {id:'palindrome',title:'回文をつくろう',icon:'🔄',cat:'国語',desc:'前から読んでも後ろから読んでも同じ言葉を探す',tags:['ことば','回文']},
  {id:'idiomsearch',title:'四字熟語探し',icon:'🈶',cat:'国語',desc:'文字の中から四字熟語を順番に見つける',tags:['四字熟語','探索']},
  {id:'dagashi',title:'だがしやさん',icon:'🍭',cat:'生活',desc:'予算の中で買い物し、おつりを考える',tags:['お金','買い物']},
  {id:'moneycount',title:'お金を数えよう',icon:'🪙',cat:'生活',desc:'並んだ硬貨の合計金額を答える',tags:['硬貨','計算']},
  {id:'exchange',title:'両替てんびん',icon:'⚖️',cat:'生活',desc:'同じ金額になる硬貨の組み合わせを選ぶ',tags:['両替','等価']},
  {id:'threepoint',title:'スリーポイントゲーム',icon:'🏀',cat:'息抜き',desc:'タイミングを合わせてシュートを決める',tags:['タイミング','レク']},
  {id:'flatoreHub',title:'フラトレ',icon:'🧠',cat:'認知',desc:'集中・記憶・判断に取り組む、にじフラのオリジナル療育ゲーム',tags:['フラトレ','集中','記憶','判断'],href:'flatore.html?v=20260902-59',noContext:true,profile:{difficulty:2,age:'全学年',minutes:'5〜10分',aim:'実行機能・注意・記憶・判断'}},
  {id:'movementHub',title:'運動あそび',icon:'🏃',cat:'運動',desc:'見る・反応する・体を動かす活動につながる運動あそび',tags:['運動','ビジョン','反応'],href:'movement.html?v=20260902-59',noContext:true,profile:{difficulty:2,age:'全学年',minutes:'5〜10分',aim:'運動・視覚反応・身体コントロール'}},
  {id:'dangerHub',title:'危険予知',icon:'⚠️',cat:'安全',desc:'身近な場面から安全な行動を考えるトレーニング',tags:['危険予知','安全','判断'],href:'danger_game.html?v=20260902-59',noContext:true,profile:{difficulty:2,age:'全学年',minutes:'5〜10分',aim:'危険認知・安全判断・行動選択'}},
  {id:'cognitiveHub',title:'10分チェック',icon:'🧩',cat:'認知',desc:'短時間の課題で、取り組み方や得意・苦手の傾向を確認',tags:['10分チェック','認知','確認'],href:'cognitive_check_10min.html?v=20260902-59',noContext:true,profile:{difficulty:2,age:'全学年',minutes:'5〜10分',aim:'注意・記憶・認知・判断の参考確認'}},
  {id:'sstHub',title:'SST',icon:'💬',cat:'SST',desc:'気持ち・伝え方・相手の立場・実生活の場面を練習',tags:['SST','気持ち','コミュニケーション'],href:'sst.html?v=20260902-59',noContext:true,profile:{difficulty:2,age:'全学年',minutes:'5〜10分',aim:'社会性・感情理解・コミュニケーション'}},
  {id:'shapePuzzle',title:'かたちパズル',icon:'🧩',cat:'認知',desc:'ピースをくみあわせて、かたちを完成させよう！',tags:['空間認知','図形','試行錯誤'],href:'shape_puzzle.html?v=20260901-4',noContext:true,profile:{difficulty:2,age:'全学年',minutes:'5〜10分',aim:'視空間認知・形の構成・試行錯誤'}},
  {id:'flagGame',title:'国旗ゲーム',icon:'🌏',cat:'社会',desc:'国旗を見て、覚えて、くらべて、世界の国を楽しく学ぼう！',tags:['国旗','世界','視覚認知'],href:'flag_game.html?v=20260902-1',noContext:true,profile:{difficulty:2,age:'全学年',minutes:'5〜10分',aim:'視覚認知・照合・記憶・選択判断'}}
];
