'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname,'..');
const htmlPath = path.join(root,'moon_jump.html');
assert.ok(fs.existsSync(htmlPath),'moon_jump.html must exist');
const html = fs.readFileSync(htmlPath,'utf8');
const corePath = path.join(root,'assets','moon_jump_core.js');
assert.ok(fs.existsSync(corePath),'assets/moon_jump_core.js must exist');
const core = require(corePath);
assert.strictEqual(core.MOON_DISTANCE_KM,384400,'moon distance must be 384,400 km');
assert.strictEqual(core.TARGET_SECONDS,300,'target duration must be 300 seconds (5 min)');
assert.ok(Math.abs(core.KM_PER_SECOND - 1281.3333333333333) < 1e-9,'distance rate must match moon distance / 300 sec');
assert.strictEqual(core.distanceAtSeconds(0),0);
assert.strictEqual(core.distanceAtSeconds(150),192200);
assert.strictEqual(core.distanceAtSeconds(300),384400);
assert.strictEqual(core.distanceAtSeconds(999),384400,'distance must clamp at the moon');
assert.strictEqual(core.remainingKmAtSeconds(300),0);
assert.strictEqual(core.progressAtSeconds(150),50);
assert.strictEqual(core.rectsOverlap({x:0,y:0,w:20,h:20},{x:10,y:10,w:20,h:20}),true,'overlap must collide');
assert.strictEqual(core.rectsOverlap({x:0,y:0,w:20,h:20},{x:21,y:0,w:20,h:20}),false,'separate rectangles must not collide');
assert.match(html,/id="gameCanvas"/,'game must use a canvas play field');
assert.match(html,/id="distanceKm"/,'HUD must show travelled distance');
assert.match(html,/id="remainingKm"/,'HUD must show remaining distance');
assert.match(html,/id="speedKm"/,'HUD must show km per second');
assert.match(html,/1秒で約1,281km/,'player must be told the per-second distance');
assert.match(html,/addEventListener\(['"]pointerdown['"]/,'gameplay must support tap/pointer input');
assert.match(html,/function\s+handleTap\s*\(/,'tap handler must exist');
assert.match(html,/endGame\(['"]obstacle['"]\s*,/,'obstacle collision must immediately end the game');
assert.match(html,/384,400km/,'clear/result copy must communicate full moon distance');
assert.match(html,/月に到着/,'clear state must celebrate reaching the moon');
assert.match(html,/隕石|人工衛星|宇宙ゴミ/,'game must contain space obstacles');
console.log('PASS moon jump core/game requirements');
