const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const catalog=fs.readFileSync(path.join(root,'assets','game_catalog.js'),'utf8');
const vm=require('vm');
const sandbox={window:{}}; vm.createContext(sandbox); vm.runInContext(catalog,sandbox);
const games=sandbox.window.NIJI_GAMES||[];
const start=html.indexOf('<div class="home-game-grid" id="gameGrid">');
const end=html.indexOf('<div id="emptyState"', start);
if(start<0||end<0) throw new Error('game grid boundaries missing');
const gridHtml=html.slice(start,end);
const staticCards=[...gridHtml.matchAll(/<article class="home-game-card[^>]*data-id="([^"]+)"/g)].map(m=>m[1]);
if(games.length!==84) throw new Error(`catalog expected 84, got ${games.length}`);
if(staticCards.length!==84) throw new Error(`index must contain 84 static game cards, got ${staticCards.length}`);
const missing=games.map(g=>g.id).filter(id=>!staticCards.includes(id));
if(missing.length) throw new Error('static cards missing: '+missing.join(','));
const dup=staticCards.filter((id,i)=>staticCards.indexOf(id)!==i);
if(dup.length) throw new Error('duplicate static cards: '+[...new Set(dup)].join(','));
console.log('PASS: index gameGrid has exactly 84 static fallback cards');
