const fs=require('fs'),assert=require('assert');
const html=fs.readFileSync(__dirname+'/../train_driver.html','utf8');
const {load}=require('./train_test_loader');
const {T}=load();

assert(html.includes('id="cabTopbar"'),'new cab topbar must exist');
assert(html.includes('id="stationPanel"'),'station guidance panel must exist');
assert(html.includes('id="speedDial"'),'large speed dial must exist');
assert(html.includes('id="masconLever"'),'large visual mascon lever must exist');
assert(html.includes('id="doorPanel"'),'door panel must exist');
assert(html.includes('id="routeProgress"'),'route progress must exist');
assert.equal(T.nextNotch('N','power'),'P1');
assert.equal(T.nextNotch('P1','power'),'P2');
assert.equal(T.nextNotch('P5','power'),'P5');
assert.equal(T.nextNotch('P2','brake'),'P1');
assert.equal(T.nextNotch('P1','brake'),'N');
assert.equal(T.nextNotch('N','brake'),'B1');
assert.equal(T.nextNotch('B6','brake'),'B7');
assert.equal(T.nextNotch('B7','brake'),'B7');
assert.equal(T.guidanceStage(700),'cruise');
assert.equal(T.guidanceStage(500),'approach');
assert.equal(T.guidanceStage(300),'braking');
assert.equal(T.guidanceStage(100),'final');
assert.equal(T.guidanceStage(0),'stop');
assert.equal(T.canOperateDoor({awaitDeparture:true,speedKph:0.1}),true);
assert.equal(T.canOperateDoor({awaitDeparture:false,speedKph:0}),false);
assert.equal(T.canOperateDoor({awaitDeparture:true,speedKph:2}),false);
assert(/mode='expert'/.test(html),'expert operation should be the default');
assert(html.includes("keydown"),'keyboard controls must be wired');
console.log('train_cab_ui_redesign: PASS');
