'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const htmlPath=path.join(root,'world_trip_jump.html');
const corePath=path.join(root,'assets','world_trip_core.js');
assert.ok(fs.existsSync(htmlPath),'world_trip_jump.html must exist');
assert.ok(fs.existsSync(corePath),'assets/world_trip_core.js must exist');
const Core=require(corePath);
assert.strictEqual(Core.EARTH_CIRCUMFERENCE_KM,40075,'earth route distance must be 40,075 km');
assert.strictEqual(Core.TARGET_SECONDS,300,'target duration must be 300 seconds');
assert.ok(Math.abs(Core.KM_PER_SECOND-(40075/300))<1e-9,'km per second must equal circumference / 300');
assert.strictEqual(Core.distanceAtSeconds(0),0);
assert.strictEqual(Core.distanceAtSeconds(150),20038);
assert.strictEqual(Core.distanceAtSeconds(300),40075);
assert.strictEqual(Core.distanceAtSeconds(999),40075,'distance must clamp at one lap');
assert.strictEqual(Core.remainingKmAtSeconds(300),0);
assert.strictEqual(Core.progressAtSeconds(150),50);
assert.ok(Array.isArray(Core.ROUTE_SCENES)&&Core.ROUTE_SCENES.length>=15,'route must contain at least 15 world scenes');
assert.strictEqual(Core.ROUTE_SCENES[0].id,'asakusa','route must start at Asakusa');
assert.strictEqual(Core.ROUTE_SCENES.at(-1).id,'skytree','route must finish at Tokyo Skytree');
for(const scene of Core.ROUTE_SCENES){
  assert.ok(scene.name&&scene.country,'each scene must have a place name and country/area');
  assert.ok(Array.isArray(scene.obstacles)&&scene.obstacles.length>=2,'each scene must have local obstacle types');
}
assert.strictEqual(Core.sceneAtProgress(0).id,'asakusa');
assert.strictEqual(Core.sceneAtProgress(100).id,'skytree');
assert.strictEqual(Core.rectsOverlap({x:0,y:0,w:20,h:20},{x:10,y:10,w:20,h:20}),true);
assert.strictEqual(Core.rectsOverlap({x:0,y:0,w:20,h:20},{x:21,y:0,w:20,h:20}),false);
const html=fs.readFileSync(htmlPath,'utf8');
assert.match(html,/id="gameCanvas"/,'game must have canvas play field');
assert.match(html,/id="distanceKm"/,'HUD must show distance travelled');
assert.match(html,/id="remainingKm"/,'HUD must show remaining distance');
assert.match(html,/id="placeName"/,'HUD must show current place');
assert.match(html,/1秒で約134km/,'player must be told approximate speed');
assert.match(html,/addEventListener\(['"]click['"]/,'tap/pointer input must be supported');
assert.match(html,/function\s+handleTap\s*\(/,'tap handler must exist');
assert.match(html,/endGame\(['"]obstacle['"]\s*,/,'obstacle collision must immediately end game');
assert.match(html,/浅草/,'start location must be Asakusa');
assert.match(html,/スカイツリー/,'goal must be Tokyo Skytree');
assert.match(html,/40,075km/,'full lap distance must be communicated');
assert.match(html,/車|タクシー/,'road vehicles must appear as obstacles');
assert.match(html,/船|ボート/,'sea obstacles must appear');
assert.match(html,/人|歩行者/,'people must appear as obstacles');
assert.match(html,/鳥|カモメ|ハト/,'birds must appear as obstacles');
assert.match(html,/東京|ハワイ|サンフランシスコ|ニューヨーク|リオ|パリ|エジプト|インド|中国/,'world route landmarks must be represented');
console.log('PASS world trip jump core/game requirements');
